# 11. 문제들에 대비하기

### 에러 핸들링 error handling

**에러 발생에 대배하지 않으면 프로그램이 종료됨**

```javascript
console.log('에러 발생 전');

// ⚠️ 오류를 발생시키는 코드
(3).split('');

// 출력되지 않음
console.log('에러 발생 후');
```

### 자바스크립트의 에러 핸들링

[👉 MDN 문서 보기](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch)

`try ~ cath` **문**

- **`try` 블록**
    - **에러 발생 여지가 있는** 코드 포함
    - 이곳에서 발생한 에러는 프로그램을 멈추지 않음
- **`catch` 블록**
    - 에러 발생시 실행할 코드 포함
    - 발생한 오류 객체를 인자로 받음

```javascript
const arr = ['ABC', '가나다', 123, '123'];

function getLetterArray (str) {
  // 💡 인자로 어떤 타입의 값이 주어질지 모르는 상황
  try {
    return str.split('');

  } catch (e) {
    console.error('🛑 에러!!', e);
    return [];
  }
}

arr.forEach(i => {
  console.log(getLetterArray(i));
});
```

- **`finally` 블록**
    - 오류가 발생 여부와 관계없이 한 번 실행되는 코드 포함
    - 아래와 같은 경우 널리 사용

```javascript
function connect () { console.log('☀️', '통신 연결'); }
function disconnect () { console.log('🌙', '통신 연결 해제'); }
function sendArray (arr) { console.log('전송', arr); }

function sendStringAsArray (str) {
  connect();

  try {
    sendArray(str.split(''));
    return true;

  } catch (e) {
    console.error('🛑 에러!!', e);
    return false;

  } finally {
    // 💡 전송 성공 여부와 관계없이 연결은 끊어야 함
    disconnect();
    console.log('- - - - - - - -');
  }

  // ❓ 이곳에 넣는 것과 무엇이 다른가?
  // 아래로 대체하여 실행해 볼 것
  // disconnect();
  // console.log('- - - - - - - -');
}

['ABC', '가나다', 123, '123'].forEach(i => {
  console.log(
    sendStringAsArray(i) 
    ? '[성공]' : '[실패]', '\n\n'
  );
});
```

### Error 객체

- 에러 발생 시 **던져지는** *thrown* 객체
- 에러에 대한 정보를 담고 있음
- 💡 에러가 발생하지 않아도, 직접 생성하여 던지기 가능
- [👉 MDN 문서 보기](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error)

**기본 생성과 사용법**

```javascript
const error = new Error('뭔가 잘못됐어');

console.error(error);
```

```javascript
// 두 번째 인자로 이유를 명시할 수도 있음
const error = new Error(
  '뭔가 잘못됐어',
  { cause: '뭘 잘못했으니까' }
);

console.error(error);
```

- **기본 인스턴스 프로퍼티와 메서드**

```javascript
console.log(error.name);
console.log(error.message);

// cause를 입력했을 경우
console.log(error.cause);

// 에러 자체를 로그 출력하면 나오는 문구
console.log(error.toString());
```

- **⭐ 의도적으로 에러 발생시키기**

```javascript
throw new Error('의도적 에러');
```

**에러의 종류**

- **⭐ 아래의 에러들은 모두 Error부터 상속받음**
- 어떤 문제에 의한 에러인지 쉽게 식별 가능하도록 함
- [👉 기타 에러 유형 MDN 문서 보기](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error#%EC%98%A4%EB%A5%98_%EC%9C%A0%ED%98%95)

| 주요 에러 | 설명 |
| --- | --- |
| SyntaxError | 문법에 이상이 있을 때 |
| TypeError | 주어진 명령에 적절한 자료형이 아닐 때 |
| ReferenceError | 잘못된 값을 참조했을 때 |
| RangeError | 유효한 범위를 벗어나는 숫자가 사용되었을 때 |

```javascript
const errorFuncs = [
  // 자료형에 맞지 않는 메서드 호출
  () => { (3).split(''); },

  // 선언되지 않은 함수 호출
  () => { hello(); },

  // 부적절한 숫자를 인자로 전달
  () => { (123.45).toFixed(-1); }
];
```

- **오류에 종류에 따라 대처하기**

```javascript
errorFuncs.forEach(func => {
  try {
    func();

  } catch (e) {
    if (e instanceof TypeError) {
      console.error('자료형 확인하세요.');
      return;
    }
    if (e instanceof ReferenceError) {
      console.error('선언 안 된 거 쓴 거 없는지 확인하세요.');
      return;
    }
    console.error('아니, 뭘 한 거에요?');
  }
});
```

- **직접 오류를 생성하여 던지기 ⇒ 컴퓨터가 인지하지 못하는 에러 수동 발생**

```javascript
// 특정 월의 당번으로 지원하는 함수
function applyForMonth (date) {
  try {
    if (typeof date !== 'number') {
      throw new TypeError('숫자로 입력해주세요.');
    }
    if (date < 1 || date > 12) {
      throw new RangeError('유효한 월을 입력해주세요.');
    }

    console.log(`${date}월 당번으로 등록되셨습니다.`);

  } catch (e) {
    console.error('🛑 에러 발생!', e);
    console.log('다시 등록해주세요.');
  }
}
```

```javascript
applyForMonth(5);
```

```javascript
applyForMonth('5'); // TypeError
```

```javascript
applyForMonth(13); // RangeError
```

**커스텀 에러 만들기**

- [👉 MDN 문서 보기](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Error#%EC%82%AC%EC%9A%A9%EC%9E%90_%EC%A0%95%EC%9D%98_%EC%97%90%EB%9F%AC_%ED%83%80%EC%9E%85)

```javascript
class VendingMachineError extends Error {
  constructor (errorName, ...params) {
    super(...params);

    this.name = 'VendingMachineError';

		const errorMessages = {
      '품절': '품절된 상품입니다.',
      '금액부족': '잔액이 부족합니다.',
      '선택오류': '존재하지 않는 음료입니다.'
    };

    this.message = errorMessages[errorName] || '';
  }
}
```

```javascript
class VendingMachine{
constructor() {
    this.product = {
      cola: { price: 1000, qty: 10 },
      soda: { price: 1000, qty: 0 },
      coffee: { price: 1500, qty: 1 }
    };
  }

  order (product, qty, money) {
    try {
		 if (!this.product[product]) {
        throw new VendingMachineError("선택오류");
      }

      if (this.product[product].qty < qty) {
        throw new VendingMachineError("품절");
      }

      if (this.product[product].price * qty > money) {
        throw new VendingMachineError("금액부족");
      }

      this.product[product].qty -= qty;
      console.log(product + "를 " + qty + "개 주문 완료");
    } catch (e) {
      console.error(e.message);
    }
  }
}
```

```javascript
const vm1 = new VendingMachine();
vm1.order("cola", 1, 1000);
vm1.order("soda", 1, 1000);
vm1.order("coffee", 1, 1000);
vm1.order("lemonAde", 1, 1000);
```

### 에러 버블링 error bubbling

**다른 함수를 호출했을 때**

- 에러 발생시 해당 함수에서 잡지 않으면 호출한 곳으로 던져짐
- 다중 호출시 에러를 핸들링하는 코드가 있는 호출자까지 전달됨
- ⭐ 에러는 가능한 발생 곳 가까이서 처리하는 것이 좋음

```javascript
function func1 () {
  throw new Error('에러');
}

function func2 () {
  func1();
}

function func3 () {
  func2();
}

function func4 () {
  try {
    func3();

  } catch (e) {
    console.error(e);
  }
  console.log('실행완료');
}

func4();
```

- 예시 코드 ⇒ 사장 > 부장 > 대리 > 사원 단계로 일을 시켰을 때

```javascript
function func1 (e) { // 사원
  try {
    if (e) { throw e }
    console.log('저 가 봐도 되죠?');
    console.log('- - - - - - - - - -');

  } catch (e) {
    if (e instanceof SyntaxError) {
      console.error('저 이건 알아요!', e);
      console.log('- - - - - - - - - -');
      return;
    }
    console.log('대리님, 이거 뭐에요?');
    throw e; // 💡 처리하지 못하는 에러는 윗선으로 던짐
  }
}
```

```javascript
function func2 (e) { // 대리
  try {
    func1(e);
  } catch (e) {
    if (e instanceof TypeError) {
      console.error('내가 할 테니 가봐요.', e);
      console.log('- - - - - - - - - -');
      return;
    }
    console.log('부장님, 이건 제 선에서 안 되겠습니다.');
    throw e;
  }
}
```

```javascript
function func3 (e) { // 부장
  try {
    func2(e);
  } catch (e) {
    if (e instanceof ReferenceError) {
      console.error('잘 하자, 응?', e);
      console.log('- - - - - - - - - -');
      return;
    }
    console.log('사장님, 이것 좀 보셔야겠습니다.');
    throw e;
  }
}
```

```javascript
function func4 (e) { // 사장
  try {
    func3(e);

  } catch (e) {
    console.error('전원 집합.', e);
  }
}
```

```javascript
func4();
```

```javascript
func4(new SyntaxError());
```

```javascript
func4(new TypeError());
```

```javascript
func4(new ReferenceError);
```

```javascript
func4(new RangeError);
```

### Var 지양하기

**`var` : `let`과 `const`가 생기기 전 변수 선언에 사용되던 문**

⇒ 각종 문제점들을 갖고 있으므로 오늘날에는 사용하지 않을 것을 권장

- **선언 없이도 사용 가능**

```javascript
notDeclared = 1; // 미리 선언한 부분이 없을 시 var로 만들어짐
console.log(notDeclared);
```

```javascript
// num이 var로 선언된 것
for (num of [1, 2, 3]) {
  console.log(num);
}
```

- **재선언 가능 ⇒** 코딩 중 실수의 여지가 됨

```javascript
let a = 1;
let a = 2; // ⚠️ 오류
```

```javascript
const b = 1;
const b = 2; // ⚠️ 오류
```

```javascript
var c = 1;
var c = 2;
```

- **블록 레벨 스코프 무시**

```javascript
let num1 = 1;
{
  let num1 = 2;
  {
    let num1 = 3;
  }
}

console.log(num1);
```

```javascript
var num2 = 1;
{
  var num2 = 2;
  {
    var num2 = 3;
  }
}

console.log(num2);
```

```javascript
// for문의 스코프도 무시
for (var i = 0; i < 5; i++) {
  var pow2 = i ** 2;
  console.log(pow2);
}

console.log(i, pow2);
```

- **함수의 스코프는 유효함 ⇒** • [🔗 IIFE](https://www.yalco.kr/@javascript/4-4)가 사용되었던 이유

```javascript
var num3 = 1;

function func1 () {
  var num3 = 2;
  return num3;
}

console.log(num3);
console.log(func1());
```

- 호이스팅
    - 엄연히는 `let`도 호이스팅 되지만 `undefined`로 초기화되지 않는 것
    - 초기화되기 이전의 영역: [🔗 TDZ에 속함](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/let#%EC%8B%9C%EA%B0%84%EC%83%81_%EC%82%AC%EA%B0%81%EC%A7%80%EB%8C%80)

```javascript
console.log(hoisted1); // ⚠️ 오류
```

```javascript
console.log(hoisted1); // 💡 오류발생 X, 대신 undefined 반환

var hoisted1 = 'Hello';

console.log(hoisted1)
```

```javascript
console.log(hoisted2); // ⚠️ 오류

let hoisted2 = 'Hello';

console.log(hoisted2)
```

### 엄격모드 strict mode

[👉 MDN 문서 보기](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Strict_mode)

기존의 **느슨한** 모드에서 허용되던, 문제를 유발할 수 있는 코드들에 오류를 발생시킴

**엄격 모드의 적용방법과 그 효과들 예시**

**ⓛ 선언되지 않은 변수 사용시 오류 발생 *+ 범위별 적용 방법***

```javascript
notDeclared = 1; // 💡 암묵적으로 전역 var 변수로 선언
```

```javascript
// ⚠️ 새로고침 후 실행해볼 것
// 선언되지 않은 변수 사용 금지
'use strict'; // 쌍따옴표도 가능

notDeclared = 1; // 오류 발생!
```

- 위와 같이 자바스크립트 **문서 최상단**에 작성 - *문서 전체에 적용*
- **문서, script 태그별로만** 적용 - 여러 `.js`파일이 페이지에 사용될 시 각각 작성해야 함

```javascript
<!DOCTYPE html>
<html lang="ko">
<head>
<script src="./1.js"></script>
<script src="./2.js"></script>
</head>
</html>
```

```javascript
// 1.js
'use strict';
x = 1;
console.log(x); // 오류 발생
```

```javascript
// 2.js
y = 2;
console.log(y); // 오류 발생하지 않음
```

- 특정 **함수의 최상단**에 작성 - 해당 함수에만 적용

```javascript
notDec1 = 1;

function strictFunc () {
'use strict';

 notDec2 = 2;
 console.log(notDec2);
}

console.log(notDec1);
strictFunc();
```

**② 변수, 함수, 인자 등 삭제불가한 것을 삭제시 오류 발생**

```javascript
// 실제로 지워지지도 않지만 오류를 발생시키지도 않음

let toDelete1 = 1;
delete toDelete1;

console.log('1.', toDelete1);
```

```javascript
function funcToDel1 () { console.log(true); }
delete funcToDel1;

console.log('2.', funcToDel1);
```

```javascript
'use strict';

let toDelete2 = 1;
delete toDelete2;
```

```javascript
'use strict';

function funcToDel2 () { console.log(true); }
delete funcToDel2;
```

**③ 인자명 중복시 오류 발생**

```javascript
// 'use strict';

function add(x, x) {
  return x + x;
}

console.log(add(1, 2));
```

**기타 기능들은 아래의 링크에서 확인**

[👉 MDN 문서 보기](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Strict_mode)

### **실무에서의 엄격 모드**

- 클래스나 모듈*(등 ES6와 그 이후의 기능들)* 사용시 엄격 모드가 기본으로 적용됨
- 🪄 모든 문제를 방지하는 수단이 되지 않음 기억
- ⚠️ 기존 코드에 엄격모드 적용시 주의 - *예기치 못한 오류 발생 가능*

### **`?.` - 옵셔널 체이닝 *optional chaining* 연산자**

- 호출 대상이 `undefined`나 `null`이어도 **오류를 발생시키지 않음** - *대신 undefined 반환*
- **있을지 없을지 모르는 것**으로부터 값을 읽거나 실행할 때 사용
- [👉 MDN 문서 보기](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Operators/Optional_chaining)
- 결과에 `prop3`이 있다면 가져와야 하는 상황

```javascript
// 최소 undefined
// 최대 {prop1:{prop2:{prop3:'성공!'}}}
// 까지 반환하는 함수
const rand = () => Math.random() < 0.75;

const notSure = () => rand() ? {
  prop1: rand() ? {
    prop2: rand() ? {
      prop3: rand() ? '성공!' : undefined
    } : undefined
  } : undefined
} : undefined;

console.log(JSON.stringify(notSure()));
```

```javascript
const result = notSure();
console.log(JSON.stringify(result));

// ⚠️ 바로 접근하려 할 시에는 실패시 에러
console.log(result.prop1.prop2.prop3);
```

- **해결방법 ⇒ optional chaining 사용시 간단하게 해결 가능**

```javascript
// 방법 1
const result = notSure();

if (result) {
  if (result.prop1) {
    if (result.prop1.prop2) {
      console.log(result.prop1.prop2.prop3);
    }
  }
}
```

```javascript
// 방법 2
const result = notSure();

console.log(
  result
  && result.prop1
  && result.prop1.prop2
  && result.prop1.prop2.prop3
);
```

```javascript
// 방법 3
const result = notSure();

try {
  console.log(result.prop1.prop2.prop3);
} catch {
  console.log(undefined);
}
```

```javascript
// 방법4 optional chaining
const result = notSure();

console.log(
  result?.prop1?.prop2?.prop3
);
```

- **유무가 불확실한 함수를 호출할 때도 유용**

```javascript
const objs = [
  { func () { console.log(1) } },
  {},
  { func () { console.log(2) } },
  {},
  { func () { console.log(3) } },
]

objs.forEach(o => o.func?.());
```